[project]
name = "markov-ns-solver"
version = "0.1.0"
description = "Efim S. Markov: 12-Fold Spatial Matrix Core & Neural Rendering Engine (DLSS 5 Alternative)"
authors = ["Efim S. Markov <visual-reality-3hcp@example.com>"]
channels = ["conda-forge", "modular-channels"]
platforms = ["linux-64", "win-64"]

[dependencies]
max-mojo = ">=1.0.0"

[tasks]
run = "mojo markov_user_interface.mojo"

# Специальные переопределения команд запуска для разных ОС относительно корня репозитория
[target.linux-64.tasks]
run = "mojo markov_user_interface.mojo"

[target.win-64.tasks]
run = "mojo.exe markov_user_interface.mojo"
