name: Dynamic Image Comparison Test

on:
  push:
    paths:
      - 'input/**' # Запускается при обновлении картинок
      - 'scripts/**' # Полезно добавить: запустится и при обновлении самого кода

jobs:
  compare:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Использован headless-пакет, чтобы избежать падения из-за libGL.so.1
      - name: Install image processing tools
        run: pip install opencv-python-headless pillow numpy

      - name: Execute 3HCP Core and Generate Visual Diff
        run: |
          python scripts/process_comparison.py 

      - name: Commit and Push processed comparison
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # Явный пуш изменений. Если папки input изначально не было, 
          # скрипт её создаст, поэтому сохраняем и её эталонный тест
          git add input/ output/
          
          git commit -m "Auto-generated 3HCP vs DLSS visual comparison test" || exit 0
          git push
